docker-elk:
  image: sebp/elk:es231_l231_k450
  expose:
    - 5601
  ports:
    - 9200:9200
    - 5044:5044
    - 5000:5000
  volumes:
    - /var/lib/elasticsearch:/var/lib/elasticsearch
    - ./config/02-beats-input.conf:/etc/logstash/conf.d/02-beats-input.conf
    - ./config/12-json.conf:/etc/logstash/conf.d/12-json.conf

docker-haproxy:
  image: million12/haproxy:latest
  links:
    - docker-elk:elk
  volumes:
    - ./config/haproxy.cfg:/etc/haproxy/haproxy.cfg
  ports:
    - "80:80"
